services:
  db:
    image: postgres:latest
    container_name: janisty_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  janisty:
    image: janisty
    build:
      context: .
      dockerfile: janisty/janisty/Dockerfile

  janisty.client:
    image: janisty.client
    build:
      context: .
      dockerfile: janisty/janisty.Client/Dockerfile

